<div class="form-list" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">
  <?php foreach ($this->getProducts() as $products):?>
  <div>
    <span>
        <input type="radio" title="<?php  $products->productName ?>" name="espayProduct" value="<?php echo $products->productCode ?>:<?php echo $products->bankCode ?> " />
    </span>
    <label><?php echo  $products->productName ?></label>

  </div>

  <?php endforeach?>

</div>
<div>
    <?php echo $this->getMethod()->getConfigData('message');?>
</div>
